# Cloudflare Workers設定ファイル
name = "chinese-food-app-proxy"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# 環境変数（本番環境用）
# 実際のAPIキーはCloudflareダッシュボードで設定
[vars]
# HOTPEPPER_API_KEY = "your_actual_api_key_here"  # この行はコメントアウト

# 開発環境設定
[env.development]
vars = { }

# 本番環境設定
[env.production]
vars = { }

# ルート設定
[[routes]]
pattern = "chinese-food-app-proxy.*.workers.dev/*"
zone_name = ""