# Cloudflare Workers設定ファイル
name = "chinese-food-app-proxy"
main = "src/worker-production.js"
compatibility_date = "2024-01-01"

# 環境変数（本番環境用）
# 実際のAPIキーはCloudflareダッシュボードで設定
[vars]
# USE_MOCK_RESPONSE = "true"  # 実際のAPI使用のためコメントアウト
# HOTPEPPER_API_KEY = "your_actual_api_key_here"  # この行はコメントアウト

# 開発環境設定
[env.development]
vars = { ENVIRONMENT = "development" }

# 本番環境設定
[env.production]
vars = { ENVIRONMENT = "production" }

# ルート設定（Workers.devサブドメインを使用）