// Mocks generated by Mockito 5.4.6 from annotations
// in chinese_food_app/test/unit/presentation/providers/area_search_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:chinese_food_app/domain/entities/store.dart' as _i4;
import 'package:chinese_food_app/domain/repositories/store_repository.dart'
    as _i2;
import 'package:chinese_food_app/presentation/providers/store_provider.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStoreRepository_0 extends _i1.SmartFake
    implements _i2.StoreRepository {
  _FakeStoreRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StoreProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreProvider extends _i1.Mock implements _i3.StoreProvider {
  MockStoreProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.Store> get searchResults => (super.noSuchMethod(
        Invocation.getter(#searchResults),
        returnValue: <_i4.Store>[],
      ) as List<_i4.Store>);

  @override
  List<_i4.Store> get swipeStores => (super.noSuchMethod(
        Invocation.getter(#swipeStores),
        returnValue: <_i4.Store>[],
      ) as List<_i4.Store>);

  @override
  List<_i4.Store> get stores => (super.noSuchMethod(
        Invocation.getter(#stores),
        returnValue: <_i4.Store>[],
      ) as List<_i4.Store>);

  @override
  List<_i4.Store> get wantToGoStores => (super.noSuchMethod(
        Invocation.getter(#wantToGoStores),
        returnValue: <_i4.Store>[],
      ) as List<_i4.Store>);

  @override
  List<_i4.Store> get visitedStores => (super.noSuchMethod(
        Invocation.getter(#visitedStores),
        returnValue: <_i4.Store>[],
      ) as List<_i4.Store>);

  @override
  List<_i4.Store> get badStores => (super.noSuchMethod(
        Invocation.getter(#badStores),
        returnValue: <_i4.Store>[],
      ) as List<_i4.Store>);

  @override
  List<_i4.Store> get newStores => (super.noSuchMethod(
        Invocation.getter(#newStores),
        returnValue: <_i4.Store>[],
      ) as List<_i4.Store>);

  @override
  _i2.StoreRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeStoreRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.StoreRepository);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadStores() => (super.noSuchMethod(
        Invocation.method(
          #loadStores,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateStoreStatus(
    String? storeId,
    _i4.StoreStatus? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStoreStatus,
          [
            storeId,
            newStatus,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveSwipedStore(
    _i4.Store? store,
    _i4.StoreStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSwipedStore,
          [
            store,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addStore(_i4.Store? store) => (super.noSuchMethod(
        Invocation.method(
          #addStore,
          [store],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllStores() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllStores,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshCache() => super.noSuchMethod(
        Invocation.method(
          #refreshCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadNewStoresFromApi({
    double? lat,
    double? lng,
    String? address,
    String? keyword = '中華',
    int? range = 3,
    int? count = 10,
    int? start = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadNewStoresFromApi,
          [],
          {
            #lat: lat,
            #lng: lng,
            #address: address,
            #keyword: keyword,
            #range: range,
            #count: count,
            #start: start,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadSwipeStores({
    required double? lat,
    required double? lng,
    int? range = 3,
    int? count = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadSwipeStores,
          [],
          {
            #lat: lat,
            #lng: lng,
            #range: range,
            #count: count,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadMoreSwipeStores({
    required double? lat,
    required double? lng,
    int? range = 3,
    int? count = 20,
    required int? start,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreSwipeStores,
          [],
          {
            #lat: lat,
            #lng: lng,
            #range: range,
            #count: count,
            #start: start,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> tryRecoverFromDatabaseError() => (super.noSuchMethod(
        Invocation.method(
          #tryRecoverFromDatabaseError,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
