// Mocks generated by Mockito 5.4.6 from annotations
// in chinese_food_app/test/widget/pages/visit_record/visit_record_form_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chinese_food_app/domain/entities/visit_record.dart' as _i2;
import 'package:chinese_food_app/domain/usecases/add_visit_record_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVisitRecord_0 extends _i1.SmartFake implements _i2.VisitRecord {
  _FakeVisitRecord_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddVisitRecordUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddVisitRecordUsecase extends _i1.Mock
    implements _i3.AddVisitRecordUsecase {
  MockAddVisitRecordUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.VisitRecord> call({
    required String? storeId,
    required DateTime? visitedAt,
    required String? menu,
    required String? memo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #storeId: storeId,
            #visitedAt: visitedAt,
            #menu: menu,
            #memo: memo,
          },
        ),
        returnValue: _i4.Future<_i2.VisitRecord>.value(_FakeVisitRecord_0(
          this,
          Invocation.method(
            #call,
            [],
            {
              #storeId: storeId,
              #visitedAt: visitedAt,
              #menu: menu,
              #memo: memo,
            },
          ),
        )),
      ) as _i4.Future<_i2.VisitRecord>);
}
