// Mocks generated by Mockito 5.4.6 from annotations
// in chinese_food_app/test/unit/domain/usecases/add_visit_record_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chinese_food_app/core/types/result.dart' as _i5;
import 'package:chinese_food_app/data/datasources/hotpepper_proxy_datasource.dart'
    as _i3;
import 'package:chinese_food_app/data/models/hotpepper_store_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHotpepperSearchResponse_0 extends _i1.SmartFake
    implements _i2.HotpepperSearchResponse {
  _FakeHotpepperSearchResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HotpepperProxyDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotpepperProxyDatasource extends _i1.Mock
    implements _i3.HotpepperProxyDatasource {
  MockHotpepperProxyDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HotpepperSearchResponse> searchStores({
    double? lat,
    double? lng,
    String? address,
    String? keyword,
    int? range = 3,
    int? count = 20,
    int? start = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchStores,
          [],
          {
            #lat: lat,
            #lng: lng,
            #address: address,
            #keyword: keyword,
            #range: range,
            #count: count,
            #start: start,
          },
        ),
        returnValue: _i4.Future<_i2.HotpepperSearchResponse>.value(
            _FakeHotpepperSearchResponse_0(
          this,
          Invocation.method(
            #searchStores,
            [],
            {
              #lat: lat,
              #lng: lng,
              #address: address,
              #keyword: keyword,
              #range: range,
              #count: count,
              #start: start,
            },
          ),
        )),
      ) as _i4.Future<_i2.HotpepperSearchResponse>);

  @override
  _i4.Future<_i5.Result<_i2.HotpepperSearchResponse>> searchStoresResult({
    double? lat,
    double? lng,
    String? address,
    String? keyword,
    int? range = 3,
    int? count = 20,
    int? start = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchStoresResult,
          [],
          {
            #lat: lat,
            #lng: lng,
            #address: address,
            #keyword: keyword,
            #range: range,
            #count: count,
            #start: start,
          },
        ),
        returnValue: _i4.Future<_i5.Result<_i2.HotpepperSearchResponse>>.value(
            _i6.dummyValue<_i5.Result<_i2.HotpepperSearchResponse>>(
          this,
          Invocation.method(
            #searchStoresResult,
            [],
            {
              #lat: lat,
              #lng: lng,
              #address: address,
              #keyword: keyword,
              #range: range,
              #count: count,
              #start: start,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<_i2.HotpepperSearchResponse>>);
}
