name = "chinese-food-app-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production.vars]
ALLOWED_ORIGINS = "https://your-app-domain.com"

[env.development.vars]
ALLOWED_ORIGINS = "*"

# API keys are set via Cloudflare dashboard or wrangler secret
# wrangler secret put HOTPEPPER_API_KEY
# wrangler secret put GOOGLE_MAPS_API_KEY