name = "chinese-food-app-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace bindings for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "YOUR_KV_NAMESPACE_ID_HERE"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID_HERE"

[env.production.vars]
ALLOWED_ORIGINS = "https://your-app-domain.com"

# 本番環境用のKV Namespace
[[env.production.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "YOUR_PRODUCTION_KV_NAMESPACE_ID_HERE"

[env.development.vars]
ALLOWED_ORIGINS = "*"

# API keys are set via Cloudflare dashboard or wrangler secret
# wrangler secret put HOTPEPPER_API_KEY
# wrangler secret put GOOGLE_MAPS_API_KEY

# KV Namespace setup instructions:
# 1. Create KV namespaces: wrangler kv:namespace create "RATE_LIMIT_KV"
# 2. Create preview namespace: wrangler kv:namespace create "RATE_LIMIT_KV" --preview
# 3. Update the IDs in this file with the returned namespace IDs